name = "f00-theme-inject"
main = "src/index.js"
compatibility_date = "2026-07-01"
account_id = "2e192c2d18f485155ba294ae5c9e1177"
routes = [
  { pattern = "f00.sh/*", zone_name = "f00.sh" },
  { pattern = "*.f00.sh/*", zone_name = "f00.sh" },
]
