.TH F00-TSORT 1 "2026" "f00 0.15.0-beta.1" "User Commands"
.SH NAME
f00-tsort \- perform topological sort (f00 suite)
.SH SYNOPSIS
.B f00-tsort
[\fIOPTION\fR]... [\fIARG\fR]...
.SH DESCRIPTION
perform topological sort.
Part of the
.B f00
coreutils replacement suite (pure assembly multicall).
.PP
Default mode is modern.
.B --core
selects strict GNU coreutils
.B tsort
compatible behavior where applicable.
.SH OPTIONS
Common suite options:
.TP
\fB\-\-help\fR
display help and exit
.TP
\fB\-\-version\fR
output version information and exit
.TP
\fB\-\-core\fR
strict coreutils-compatible mode
.TP
\fB\-\-json\fR
JSON summary when supported
.TP
\fB\-\-csv\fR
CSV summary when supported
.PP
See
.B f00-tsort --help
for the full flag list.
.SH AUTHOR
f00 contributors. License MIT.
.SH SEE ALSO
.BR tsort (1),
.BR f00 (1)
.PP
https://f00.sh
