.TH F00-SHA512SUM 1 "2026" "f00 0.15.0" "User Commands"
.SH NAME
f00-sha512sum \- compute and check SHA512 message digest (f00 suite)
.SH SYNOPSIS
.B f00-sha512sum
[\fIOPTION\fR]... [\fIARG\fR]...
.SH DESCRIPTION
compute and check SHA512 message digest.
Part of the
.B f00
coreutils replacement suite (pure assembly multicall).
.PP
Default mode is modern.
.B --core
selects strict GNU coreutils
.B sha512sum
compatible behavior where applicable.
.SH OPTIONS
Common suite options:
.TP
\fB\-\-help\fR
display help and exit
.TP
\fB\-\-version\fR
output version information and exit
.TP
\fB\-\-core\fR
strict coreutils-compatible mode
.TP
\fB\-\-json\fR
JSON summary when supported
.TP
\fB\-\-csv\fR
CSV summary when supported
.PP
See
.B f00-sha512sum --help
for the full flag list.
.SH AUTHOR
f00 contributors. License MIT.
.SH SEE ALSO
.BR sha512sum (1),
.BR f00 (1)
.PP
https://f00.sh
